version: '2'
services:
  mysql:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33306:3306
  redis:
    build: ./redis/
    ports:
      - 36379:6379
  fluentd:
    build: ./fluentd/
    ports:
      - "24224:24224"
